### ISSUE TITLE
undefined reference to `makeWord(unsigned short)'

### ISSUE THREAD

**Issue by aliattari** [akuma6099/MCP47FEB#4]
Back in 2019 I could this library very well with adafruit  NRF board. Now I have switched to ESP32-WROOM board. getting this error. Not sure if Arduino have updated internal codes or something. 

basically something is wrong with makeWord function. Any suggestion?

Here is the error:

libraries\MCP47FEB-master\mcp47FEB22.cpp.o:(.literal._ZN10mcp47FEB2211analogWriteEtt+0x0): undefined reference to `makeWord(unsigned short)'
libraries\MCP47FEB-master\mcp47FEB22.cpp.o: In function `mcp47FEB22::fastWrite(unsigned char, unsigned short)':
C:\Users\attari\Documents\Arduino\libraries\MCP47FEB-master/mcp47FEB22.cpp:259: undefined reference to `makeWord(unsigned short)'
libraries\MCP47FEB-master\mcp47FEB22.cpp.o: In function `mcp47FEB22::analogWrite(unsigned short, unsigned short)':
C:\Users\attari\Documents\Arduino\libraries\MCP47FEB-master/mcp47FEB22.cpp:259: undefined reference to `makeWord(unsigned short)'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Adafruit ESP32 Feather.

Thanks

**Comment by akuma6099** [comment]
Yes, the makeWord function is actually a typedef macro defined for WORD() within /Arduino/cores/{board}/Arduino.h and it is specific to the board you are programming. All this helper macro does is take in 2 8-bit values and concat them to make an unsigned 16-bit word (2 Bytes). If you look at the analogWrite function you are calling:
```
/*
Write Vout0/Vout1 register values using fastwrite method.
Values : 0-4095 (12-Bits hence the & 0x0FFF)
*/
uint8_t mcp47FEB22::analogWrite(uint16_t value1, uint16_t value2) {
  _values[0] = word((value1 & 0x0FFF));
  _values[1] = word((value2 & 0x0FFF));
  _return = 0;
  _return |= fastWrite(DAC0_REG, _values[0]);
  _return |= fastWrite(DAC1_REG, _values[1]);
  return _return;
}
```

_values[0]/[1] needs uint16_t values. If you pass in a value larger than 12 bits == 4095, we simply bitwise AND it to enforce a 12-bit result which is the maximum size of the register. It will drop bits 13->16 since we use mask 0xFFF.

Either reimplement all the Word(*) functions within this library which can vary depending on the function, or manually fix your macro definition for the board type you are using and this will compile properly. If you fix your board definition then you'll have to maintain that file as it changes with updated releases. If you fix the library side, then you can keep it to the side and use it specifically for this board you are trying to program.

**Comment by aliattari** [comment]
I simply added parentheses around the word and it fixed that.   

Thanks though,
Ali

**Comment by akuma6099** [comment]
Glad it was a simple fix! Closing.
